name: Update Directory Structure in README
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Install Tree Utility
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
    
      - name: Generate File Tree
        run: |
          echo '```text' > tree_output.txt
          tree -I '.git|node_modules|.github|.scripts' >> tree_output.txt
          echo '```' >> tree_output.txt
          echo "FILE_TREE<<DELIMITER" >> $GITHUB_ENV
          cat tree_output.txt >> $GITHUB_ENV
          echo "DELIMITER" >> $GITHUB_ENV

      - name: Run Helper Scripts
        env:
          FILE_TREE: ${{ env.FILE_TREE }}
        run: python3 .github/workflows/.scripts/update_file_tree.py

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip ci] README: update directory structure"

        