name: Update Directory Structure in README
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Install Tree Utility
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
      
      - name: Generate and Capture Tree
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          
          echo '```text' > tree_output.txt
          tree -I '.git|node_modules|.github|.scripts|tree_output.txt' --noreport --dirsfirst . >> tree_output.txt
          
          # Replace the first line in the tree "." with the Repo Name
          sed -i "1s/^\./$REPO_NAME/" tree_output.txt
          
          echo '```' >> tree_output.txt
          
          echo "FILE_TREE<<DELIMITER" >> $GITHUB_ENV
          cat tree_output.txt >> $GITHUB_ENV
          echo "DELIMITER" >> $GITHUB_ENV

      - name: Run Helper Scripts
        env:
          FILE_TREE: ${{ env.FILE_TREE }}
        run: python3 .github/workflows/.scripts/update_file_tree.py

      - name: Cleanup Temporary Files
        if: always()
        run: rm -f tree_output.txt

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip ci] README: update directory structure"

        